In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame({
    'text': ['people watch movie', 'movie write movie', 'people write comment', 'movie write comment'],
    'output': [1, 1, 0, 0]
})


In [5]:
df

,text,output
0,people watch movie,1
1,movie write movie,1
2,people write comment,0
3,movie write comment,0


In [ ]:
#Ohe hot Encoding

In [26]:


df1 = pd.DataFrame({
    'text1': ['spam', 'ham']
})

print(df1)

  text1
0  spam
1   ham


In [34]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False)

encoded = ohe.fit_transform(df1[['text1']])

print(encoded)

[[0. 1.]
 [1. 0.]]


In [ ]:
# Bag of words

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv =  CountVectorizer()

In [10]:
bow = cv.fit_transform(df['text'])
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

In [11]:
# vocablury
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'movie': 1, 'write': 4, 'comment': 0}


In [16]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 1 1 1 0]]
[[0 2 0 0 1]]
[[1 0 1 0 1]]
[[1 1 0 0 1]]


In [20]:
cv.transform(['Movie write comment and people watch movie']).toarray()

array([[1, 2, 1, 1, 1]], dtype=int64)

In [ ]:
# N gram
#Unigram

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv =  CountVectorizer(ngram_range=(1,1))

In [38]:

ugram = cv.fit_transform(df['text']).toarray()
ugram

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]], dtype=int64)

In [ ]:
#Bigram

In [42]:
cv =  CountVectorizer(ngram_range=(2,2))
bigram = cv.fit_transform(df['text']).toarray()
bigram

array([[0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0]], dtype=int64)

In [43]:
print(cv.vocabulary_)

{'people watch': 1, 'watch movie': 3, 'movie write': 0, 'write movie': 5, 'people write': 2, 'write comment': 4}


In [ ]:
# Trigram

In [40]:
cv =  CountVectorizer(ngram_range=(3,3))
trigram = cv.fit_transform(df['text']).toarray()
trigram

array([[0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0]], dtype=int64)

In [41]:
print(cv.vocabulary_)

{'people watch movie': 2, 'movie write movie': 1, 'people write comment': 3, 'movie write comment': 0}


In [ ]:
# TF-IDF

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.44809973, 0.55349232, 0.70203482, 0.        ],
       [0.        , 0.89442719, 0.        , 0.        , 0.4472136 ],
       [0.61366674, 0.        , 0.61366674, 0.        , 0.49681612],
       [0.65782931, 0.53256952, 0.        , 0.        , 0.53256952]])

In [46]:
print(tfidf.idf_)

[1.51082562 1.22314355 1.51082562 1.91629073 1.22314355]


In [47]:
print(tfidf.get_feature_names_out())

['comment' 'movie' 'people' 'watch' 'write']
